### ISSUE TITLE
wcs-manifest misses a proper abstract and longer description of the component

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-routeplanner#11]

**Comment by niettadesantis** [comment]
Also here, I'm not able to change the state of the issue, @Piiit. Should you give me other credentials to the repository? Or is it planned that I just unassign me (that's all I can do by now in here) and then you close the issue?

**Comment by Piiit** [comment]
@niettadesantis Can you please retry now... Let me know which repositories you need access to

**Comment by niettadesantis** [comment]
> @niettadesantis Can you please retry now... Let me know which repositories you need access to

Works now, thank you! There should be no other repo with this problem - in case I'll let you know. 
Do you think this description is enough?

**Comment by Piiit** [comment]
@niettadesantis Great. Which description?

**Comment by niettadesantis** [comment]
> Which description?

The description of the component - I updated it yesterday. :)

**Comment by niettadesantis** [comment]
> > Which description?
> 
> The description of the component - I updated it yesterday. Didn't you get the pull request?

It's very strange, I'm sure I saved at least the modified file... now I can't see the longer description it anymore. Anyway, I'll write it again and send you a PR!

**Comment by Piiit** [comment]
@niettadesantis Is this issue solved with https://github.com/noi-techpark/webcomp-routeplanner/pull/14? Can we close it?
