### ISSUE TITLE
Configurator: Display name of the destination: replace space with %20

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/webcomp-routeplanner#12]
In the code snippet the space inserted into the field "Display name of the destination" of the configurator in the web component store should be replaced with %20 character.

![image](https://user-images.githubusercontent.com/46811227/82557767-a548b400-9b6c-11ea-9442-7c648725bd29.png)

![image](https://user-images.githubusercontent.com/46811227/82557718-89451280-9b6c-11ea-8c38-2cd2a794c3d1.png)

**Comment by niettadesantis** [comment]
@Piiit I'm not able to assign the issue to anyone...

**Comment by niettadesantis** [comment]
> @Piiit I'm not able to assign the issue to anyone...

Works now, thank you @Piiit

**Comment by Piiit** [comment]
@niettadesantis 
I am not sure, if I interpret the request correctly :-)

Do you mean that I need to add those %20 into the wcs-manifest.json?

**Comment by niettadesantis** [comment]
No, I mean the code snippet, that gets the parameter from the configuration input field "Display name of the destination". The store writes this string into the parameter "destination-name" of the snippet.
If I write in the field "IDM Südtirol" for example, in the snippet by now there should be written "IDM%20Südtirol" instead of "IDM Südtirol" because otherwise the widget shows "IDMSüdtirol" (without space).
As I'm writing this I'm in doubt if this is actually the right way... maybe I should ask Belka to change the webcomponent so that it doesn't trims the spaces of the parameter if they're not encoded...?

**Comment by Piiit** [comment]
@niettadesantis I think you should ask Belka to fix this directly

**Comment by Piiit** [comment]
@npretto FYI

**Comment by Piiit** [comment]
@npretto @niettadesantis Forget it, the direct preview works well, the external window preview creates this error... so that is a known bug inside the store itself.

See https://github.com/noi-techpark/odh-web-components-store/issues/53
