### ISSUE TITLE
Car routing doesn't work in the WCS

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/webcomp-routeplanner#15]
In the tab "car" always appears "nessun risultato", regardless of the inserted starting point. Also in the preview tab this happens.
For comparison, in the Belka demo it works:
https://clients.belka.us/idm/routeplanner/demo/routeplanner.html

**Comment by Piiit** [comment]
@niettadesantis This is due to the missing HERE API key. I will add that now... I take the key of Belka, or do you want/need to have your own? If so, I suggest that IDM creates one.

**Comment by Piiit** [comment]
@niettadesantis Version 0.6.0 should work, please test when it is online... Thx

**Comment by niettadesantis** [comment]
Ok, I'll test it as soon as I see v. 0.6.0.
Anyway it seems strange to me that you say that the api key is missing... didn't you passed it here?
![image](https://user-images.githubusercontent.com/46811227/83861841-66e0f680-a721-11ea-9835-adb2418c3ba9.png)

**Comment by Piiit** [comment]
@niettadesantis No, that is the API key used for the map tiles, there is another one used for the routing, that was missing. Now it is fixed. I tested it 1 minute ago. You need to refresh your browser cache thou, to be sure to get the right version

**Comment by Piiit** [comment]
@niettadesantis I think, you might need also to ask Belka if we can use their key
