### ISSUE TITLE
Routeplanner doesn't adapt to the iframe height of the WCS preview box

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/webcomp-routeplanner#16]
See screenshot:
![screenshot-webcomponents opendatahub testingmachine eu-2020 06 05-10_26_07](https://user-images.githubusercontent.com/46811227/83854547-29776b80-a717-11ea-85fa-ce2142d980a8.png)
Is it something that I have to report to Belka or are you the one that has to fix it?

**Comment by Piiit** [comment]
@niettadesantis This is an issue that you should assign to Belka, not me... There is no parameter or style attribute (or it is, and not documented) ... That we could use.

**Comment by niettadesantis** [comment]
@npretto can you please check this issue? Thank you.

**Comment by Piiit** [comment]
Currently block due to https://github.com/noi-techpark/webcomp-routeplanner/issues/20

**Comment by Piiit** [comment]
@npretto @niettadesantis There is a width/height parameter now, but we need to see if we can really make it responsive with them. I need further testing, so I keep it open for now

**Comment by Piiit** [comment]
@niettadesantis @npretto We will follow this issue in a more generic way. That is, we need to understand what we need to make a web component really responsive, in height and width. See https://github.com/noi-techpark/odh-web-components-store/issues/70

**Comment by rcavaliere** [comment]
Next steps: @Piiit agrees with @niettadesantis how to close this issue

**Comment by Piiit** [comment]
@niettadesantis @npretto We will investigate this further, and during the next development cycle (Web Component Store V2) we will verify if we can solve this issue inside the web component store itself, or have some guidelines to solve such issues. I move it back to backlog until then... Please feel free to comment if you have any questions. 

Cheers,
Peter

**Comment by Piiit** [comment]
@npretto @niettadesantis Fixed inside the store, please set height to 100% in the `configurator` if you want to test it

**Comment by niettadesantis** [comment]
Works fine! Thank you.
Can we set 100% as default value in the height-field, just like in the width-field?

**Comment by Piiit** [comment]
@niettadesantis Done... and I changed tiles from HERE to OSM as well.. The routing uses still HERE though. Hope that is fine

**Comment by niettadesantis** [comment]
That's great, thank you!
