### ISSUE TITLE
As a web component user, I want to have the new route planner widget deployable from the store

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-routeplanner#30]
- [x] Final tests for v1.0.0 before going online with feedback from @niettadesantis 
- [x] Release to production store

**Comment by Piiit** [comment]
@niettadesantis Please have a look and test... move it to "Release on production" and assign me please, if you are happy with the result

**Comment by niettadesantis** [comment]
Seems all ok, you can release it.
