### ISSUE TITLE
The min-dist file has around 1.2MB, that could be a performance issue

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-routeplanner#6]

**Comment by GiovanniFrigo** [comment]
This has been addressed in the following commits:

- [Replacing moment with fecha](https://github.com/BelkaLab/webcomp-publictransport/commit/9b2d5ad64242ad02bccf968b443cf6f5dbd08e8a)
- [Running the images through image-optim](https://github.com/BelkaLab/webcomp-publictransport/commit/41004b02b61c9ca87a98e27565db94cde92cf3f4)

Both fixes are included in PR #18

The bundle size is now down to 880 KiB.

We currently see no further size reduction possible, as the main dependency is the pdf generating library which is required by product specifications.

**Comment by Piiit** [comment]
@GiovanniFrigo Cool! Thanks...
